### ISSUE TITLE
[Bug] Unable to reconstruct image URL path because the folder placement isn't being stored in Sanity

### ISSUE THREAD

**Issue by matthewharwood** [sanity-io/sanity-plugin-asset-source-cloudinary#3]
Question: From sanity, when uploading an image to Cloudinary and put said image inside a folder, How can I ensure that the sanity response will include the folder name?

Answer: According to @kmelve this currently isn't working. It would seem to be a bug or oversight in the code here:
https://github.com/sanity-io/sanity-plugin-asset-source-cloudinary/blob/master/src/components/CloudinaryAssetSource.tsx#L80

For full reference: I had a conversation with @kmelve:
https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1590429743042000

Visual Reference:

You can see that this image has a folder dir:
![image](https://user-images.githubusercontent.com/1505266/83277292-ac804b00-a186-11ea-976a-d1566ede1986.png)

You can see that this output lacks the folder dir:
![image](https://user-images.githubusercontent.com/1505266/83277306-b1dd9580-a186-11ea-82e1-01a9274fa784.png)

**Comment by kmelve** [comment]
Thanks for the report! I hope we'll be able to fix this soon.

**Comment by matthewharwood** [comment]
@kmelve bump ;) ?

**Comment by skogsmaskin** [comment]
@matthewharwood - this info exists on the asset document, however it's base64-encoded in the `source.id` field.

```
atob("eyJwdWJsaWNfaWQiOiJzYW1wbGVzL2Nsb3VkaW5hcnktZ3JvdXAiLCJyZXNvdXJjZV90eXBlIjoiaW1hZ2UiLCJ0eXBlIjoidXBsb2FkIn0=")

> {"public_id":"samples/cloudinary-group","resource_type":"image","type":"upload"}
```

`public_id` is the folder name.

**Comment by skogsmaskin** [comment]
Updated the README on this.
